version: "3"
services:
  velodyne:
    build: .
    image: velodyne
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /home/ireton/Projects/Masters/ros_ws:/root/ros_ws
      - /media/ireton/SR19/:/root/ros_ws/data
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://cpr-a200-0971:11311
      - ROS_HOSTNAME=localhost
      - ROS_IP=127.0.0.1
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
